apiVersion: nvidia.com/v1alpha1
kind: DynamoGraphDeployment
metadata:
  name: bench-minimax-kv
  namespace: default
spec:
  pvcs:
  - create: false
    name: pvc-lustre-dynamo
    size: '0'
  services:
    Frontend:
      componentType: frontend
      envFromSecret: hf-token-secret
      extraPodSpec:
        mainContainer:
          args:
          - >-
            python3 -m dynamo.frontend
            --http-port 8000
            --http-host 0.0.0.0
            --router-mode kv
            --router-reset-states
            --shared-cache-type none
            --model-name MiniMaxAI/MiniMax-M2
            --model-path /mnt/model-cache/hub/models--MiniMaxAI--MiniMax-M2.7/snapshots/d494266a4affc0d2995ba1fa35c8481cbd84294b
          command:
          - /bin/sh
          - -c
          env:
          - name: HF_HOME
            value: /mnt/model-cache
          - name: PYTHONHASHSEED
            value: "0"
          image: docker.io/ashnam/dynamo-vllm-runtime:thunderagent
          name: ''
          resources: {}
        nodeSelector:
          agentpool: ndh100pool
      replicas: 1
      volumeMounts:
      - mountPoint: /mnt/model-cache
        name: pvc-lustre-dynamo
    VllmWorker:
      componentType: worker
      envFromSecret: hf-token-secret
      extraPodSpec:
        mainContainer:
          args:
          - >-
            python3 -m dynamo.vllm
            --model /mnt/model-cache/hub/models--MiniMaxAI--MiniMax-M2.7/snapshots/d494266a4affc0d2995ba1fa35c8481cbd84294b
            --served-model-name MiniMaxAI/MiniMax-M2
            --tensor-parallel-size 4
            --block-size 16
            --kv-cache-dtype fp8
            --enable-prefix-caching
            --dyn-tool-call-parser minimax_m2
            --dyn-reasoning-parser minimax_append_think
            --kv-events-config '{"publisher":"zmq","topic":"kv-events","endpoint":"tcp://*:5571","enable_kv_cache_events":true}'
          command:
          - /bin/sh
          - -c
          env:
          - name: HF_HOME
            value: /mnt/model-cache
          - name: PYTHONHASHSEED
            value: "0"
          image: docker.io/ashnam/dynamo-vllm-runtime:thunderagent
          name: ''
          resources: {}
          workingDir: /workspace/examples/backends/vllm
        nodeSelector:
          agentpool: ndh100pool
      replicas: 2
      resources:
        limits:
          gpu: '4'
        requests:
          custom:
            ephemeral-storage: 4Gi
          gpu: '4'
      volumeMounts:
      - mountPoint: /mnt/model-cache
        name: pvc-lustre-dynamo
